import enum
from typing import List

class Region(enum.Enum):
    AL = "Albania",
    AM = "Armenia",
    AT = "Austria",
    AZ = "Azerbaijan",
    BE = "Belgium",
    BG = "Bulgaria",
    BY = "Belarus",
    CH = "Switzerland",
    CY = "Cyprus",
    CZ = "Czechia",
    DE = "Germany",
    DE_TOT = "Unknown",
    DK = "Denmark",
    EA18 = "Unknown",
    EA19 = "Unknown",
    EE = "Estonia",
    EEA30_2007 = "Unknown",
    EEA31 = "Unknown",
    EFTA = "Unknown",
    EL = "Greece",
    ES = "Spain",
    EU27_2007 = "Unknown",
    EU27_2020 = "Unknown",
    EU28 = "Unknown",
    FI = "Finland",
    FR = "France",
    FX = "Metropolitan France",
    GE = "Georgia",
    HR = "Croatia",
    HU = "Hungary",
    IE = "Ireland",
    IS = "Iceland",
    IT = "Italy",
    LI = "Liechtenstein",
    LT = "Lithuania",
    LU = "Luxembourg",
    LV = "Latvia",
    MD = "Moldova, Republic of",
    ME = "Montenegro",
    MK = "North Macedonia",
    MT = "Malta",
    NL = "Netherlands",
    NO = "Norway",
    PL = "Poland",
    PT = "Portugal",
    RO = "Romania",
    RS = "Serbia",
    RU = "Russian Federation",
    SE = "Sweden",
    SI = "Slovenia",
    SK = "Slovakia",
    SM = "San Marino",
    TR = "Türkiye",
    UA = "Ukraine",
    UK = "United Kingdom",
    XK = "Kosovo"

    @classmethod
    def actual_countries(cls):
        non_country_regions = {"EU28", "EFTA", "EEA", "EA", "EU27_2020", "EU27_2007", "EEA31", "EEA30_2007", "EA19", "EA18", "DE_TOT"}
        return [region for region in cls if region.name not in non_country_regions]
