name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        # Make sure the Poetry bin directory is in the PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Verify Poetry Installation
      run: |
        # Print Poetry version to verify installation
        poetry --version

    - name: Install dependencies
      run: |
        # Ensure Poetry is in PATH
        poetry --version
        poetry install

    - name: Run Pytest
      run: |
        # Ensure Poetry is in PATH
        poetry --version
        pytest life_expectancy

    - name: Run Pylint
      run: |
        # Ensure Poetry is in PATH
        poetry --version
        pylint life_expectancy/**/*.py
